Fixing output being eaten by npm install

diff --git a/test/packaging/bin/setup b/test/packaging/bin/setup
--- a/test/packaging/bin/setup
+++ b/test/packaging/bin/setup
@@ -1,20 +1,26 @@
 #!/bin/bash
 
-set -eo pipefail
+set -o pipefail
+
+print_and_kill_on_error() {
+  local tmp=$(mktemp)
+  $* &> "$tmp"
+  if (( $? )); then
+    echo -e "\nError running '$*':"
+    cat "$tmp"
+    rm "$tmp"
+    exit 1
+  fi
+  rm "$tmp"
+}
 
 cd ../..
 echo -n "Building latest version of SDK ... "
-tmp=$(mktemp)
-npm pack &> "$tmp"
-if (( $? )); then
-  cat "$tmp"
-  exit 1
-fi
-echo "done"
-rm "$tmp"
+print_and_kill_on_error "npm pack"
 cp mxenabled-web-widget-sdk-$(npm view . version).tgz mxenabled-web-widget-sdk-latest.tgz
+echo "done"
 
 cd - > /dev/null
 echo -n "Installing latest version of SDK ... "
-npm i ../../mxenabled-web-widget-sdk-latest.tgz --silent
+print_and_kill_on_error "npm i ../../mxenabled-web-widget-sdk-latest.tgz --silent"
 echo "done"
